version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sno_rx_16ab_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass

  ctakes:
    build: .
    image: beapen/ctakes
    restart: always
    ports:
      - 8093:8080